//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEmployeeRecord.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManager
    {
        public int ManagerID { get; set; }
        public int EmployeeID { get; set; }
        public int SectorID { get; set; }
        public int AccessLevelID { get; set; }
    
        public virtual tblAccessLevel tblAccessLevel { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblSector tblSector { get; set; }
    }
}
